
import { Job, User, UserRole, Applicant, Notification, PageView } from './types';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'TechFlow Solutions',
    location: 'San Francisco, CA (Remote)',
    type: 'Full-time',
    salaryRange: '$140k - $180k',
    description: 'We are looking for an experienced React developer to lead our dashboard team. You will be responsible for architecture and performance optimization.',
    requirements: ['React', 'TypeScript', 'Tailwind CSS', 'Performance Optimization', '5+ years experience'],
    postedDate: '2 days ago',
    logoUrl: 'https://picsum.photos/id/1/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop',
    applicantCount: 12,
    companyDescription: 'TechFlow Solutions is a pioneer in enterprise software, delivering scalable cloud solutions to Fortune 500 companies. We pride ourselves on a culture of innovation and engineering excellence.'
  },
  {
    id: '2',
    title: 'AI/ML Engineer',
    company: 'Nexus AI',
    location: 'New York, NY',
    type: 'Full-time',
    salaryRange: '$160k - $220k',
    description: 'Join our core AI team building next-gen LLM applications. Experience with Python, PyTorch, and deploying models to production is required.',
    requirements: ['Python', 'PyTorch', 'LLMs', 'Docker', 'Kubernetes'],
    postedDate: '1 week ago',
    logoUrl: 'https://picsum.photos/id/2/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop',
    applicantCount: 8,
    companyDescription: 'Nexus AI is at the forefront of artificial intelligence research and application. Our mission is to democratize access to powerful AI tools that enhance human productivity.'
  },
  {
    id: '3',
    title: 'Product Designer',
    company: 'Creative Loops',
    location: 'Austin, TX',
    type: 'Contract',
    salaryRange: '$80/hr',
    description: 'Looking for a UI/UX designer with a strong portfolio in SaaS applications. Figma mastery is a must.',
    requirements: ['Figma', 'Prototyping', 'User Research', 'Design Systems'],
    postedDate: '3 days ago',
    logoUrl: 'https://picsum.photos/id/3/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&auto=format&fit=crop',
    applicantCount: 24,
    companyDescription: 'Creative Loops is a design-first digital agency helping startups finding their visual identity. We believe in pixel-perfect designs and user-centric workflows.'
  },
  {
    id: '4',
    title: 'Backend Developer (Go)',
    company: 'StreamLine',
    location: 'Remote',
    type: 'Full-time',
    salaryRange: '$130k - $160k',
    description: 'Scale our high-throughput streaming service. Go experience is essential.',
    requirements: ['Go', 'PostgreSQL', 'Redis', 'gRPC'],
    postedDate: '5 hours ago',
    logoUrl: 'https://picsum.photos/id/4/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=800&auto=format&fit=crop',
    applicantCount: 5,
    companyDescription: 'StreamLine is the fastest growing media delivery platform. We serve millions of requests per second and handle petabytes of data daily.'
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    company: 'CloudScale Systems',
    location: 'Seattle, WA',
    type: 'Full-time',
    salaryRange: '$150k - $190k',
    description: 'Join our infrastructure team to build and maintain scalable cloud solutions. Experience with Kubernetes and CI/CD is required.',
    requirements: ['Kubernetes', 'Docker', 'Terraform', 'AWS', 'Jenkins', 'Python'],
    postedDate: '1 day ago',
    logoUrl: 'https://picsum.photos/id/5/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop',
    applicantCount: 15,
    companyDescription: 'CloudScale Systems provides enterprise-grade cloud infrastructure management solutions to help businesses scale efficiently.'
  },
  {
    id: '6',
    title: 'Mobile App Developer (React Native)',
    company: 'AppForge',
    location: 'Los Angeles, CA',
    type: 'Full-time',
    salaryRange: '$120k - $155k',
    description: 'Build cross-platform mobile applications using React Native. iOS and Android deployment experience required.',
    requirements: ['React Native', 'JavaScript', 'iOS Development', 'Android Development', 'Redux'],
    postedDate: '4 days ago',
    logoUrl: 'https://picsum.photos/id/6/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&auto=format&fit=crop',
    applicantCount: 18,
    companyDescription: 'AppForge is a leading mobile development studio creating innovative apps for Fortune 500 companies and startups alike.'
  },
  {
    id: '7',
    title: 'Data Analyst',
    company: 'InsightLabs',
    location: 'Chicago, IL',
    type: 'Full-time',
    salaryRange: '$85k - $110k',
    description: 'Analyze large datasets to drive business decisions. Strong SQL and visualization skills needed.',
    requirements: ['SQL', 'Python', 'Tableau', 'Excel', 'Statistics', 'Data Visualization'],
    postedDate: '2 days ago',
    logoUrl: 'https://picsum.photos/id/7/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop',
    applicantCount: 22,
    companyDescription: 'InsightLabs helps companies transform data into actionable insights through advanced analytics and machine learning.'
  },
  {
    id: '8',
    title: 'Cybersecurity Specialist',
    company: 'SecureNet',
    location: 'Washington, DC',
    type: 'Full-time',
    salaryRange: '$135k - $175k',
    description: 'Protect our infrastructure and applications from security threats. Experience with penetration testing preferred.',
    requirements: ['Network Security', 'Penetration Testing', 'CISSP', 'Linux', 'Security Auditing'],
    postedDate: '3 days ago',
    logoUrl: 'https://picsum.photos/id/8/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop',
    applicantCount: 9,
    companyDescription: 'SecureNet is a premier cybersecurity firm protecting government and corporate clients from advanced cyber threats.'
  },
  {
    id: '9',
    title: 'Technical Writer',
    company: 'DocuFlow',
    location: 'Remote',
    type: 'Contract',
    salaryRange: '$65/hr',
    description: 'Create comprehensive technical documentation for our API and developer tools. Strong writing and technical skills needed.',
    requirements: ['Technical Writing', 'API Documentation', 'Markdown', 'Git', 'Developer Tools'],
    postedDate: '1 week ago',
    logoUrl: 'https://picsum.photos/id/9/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800&auto=format&fit=crop',
    applicantCount: 14,
    companyDescription: 'DocuFlow specializes in developer documentation and technical content creation for SaaS companies.'
  },
  {
    id: '10',
    title: 'QA Automation Engineer',
    company: 'TestPro Solutions',
    location: 'Denver, CO',
    type: 'Full-time',
    salaryRange: '$110k - $140k',
    description: 'Design and implement automated testing frameworks. Experience with Selenium and CI/CD integration required.',
    requirements: ['Selenium', 'Java', 'Python', 'Jest', 'Continuous Integration', 'Test Automation'],
    postedDate: '6 days ago',
    logoUrl: 'https://picsum.photos/id/10/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop',
    applicantCount: 11,
    companyDescription: 'TestPro Solutions delivers cutting-edge quality assurance solutions to ensure software reliability at scale.'
  },
  {
    id: '11',
    title: 'Blockchain Developer',
    company: 'CryptoTech Innovations',
    location: 'Miami, FL',
    type: 'Full-time',
    salaryRange: '$145k - $200k',
    description: 'Build decentralized applications and smart contracts. Solidity and Web3 experience essential.',
    requirements: ['Solidity', 'Web3.js', 'Ethereum', 'Smart Contracts', 'JavaScript', 'DeFi'],
    postedDate: '5 days ago',
    logoUrl: 'https://picsum.photos/id/11/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop',
    applicantCount: 7,
    companyDescription: 'CryptoTech Innovations is pioneering the future of decentralized finance and blockchain technology.'
  },
  {
    id: '12',
    title: 'Game Developer (Unity)',
    company: 'PixelForge Studios',
    location: 'San Jose, CA',
    type: 'Full-time',
    salaryRange: '$105k - $145k',
    description: 'Create immersive gaming experiences using Unity. 3D graphics and gameplay programming skills required.',
    requirements: ['Unity', 'C#', '3D Graphics', 'Game Design', 'Physics Engine', 'Animation'],
    postedDate: '4 days ago',
    logoUrl: 'https://picsum.photos/id/12/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop',
    applicantCount: 20,
    companyDescription: 'PixelForge Studios creates award-winning indie games that push the boundaries of interactive entertainment.'
  },
  {
    id: '13',
    title: 'Cloud Solutions Architect',
    company: 'CloudWorks Global',
    location: 'Dallas, TX',
    type: 'Full-time',
    salaryRange: '$165k - $210k',
    description: 'Design enterprise cloud architecture solutions for our clients. Multi-cloud experience preferred.',
    requirements: ['AWS', 'Azure', 'Google Cloud', 'Microservices', 'Solution Architecture', 'Serverless'],
    postedDate: '1 day ago',
    logoUrl: 'https://picsum.photos/id/13/48/48',
    coverUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop',
    applicantCount: 6,
    companyDescription: 'CloudWorks Global helps enterprises migrate to and optimize their cloud infrastructure across all major platforms.'
  }
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Johnson',
  email: 'alex.j@example.com',
  role: UserRole.STUDENT,
  avatarUrl: 'https://picsum.photos/id/64/100/100',
  title: 'Software Engineer',
  bio: 'Passionate frontend developer with 3 years of experience in React ecosystems. I love building user-centric applications and staying up-to-date with the latest web technologies.',
  status: 'Active',
  joinedDate: '2023-11-15',
  university: 'Stanford University',
  major: 'Computer Science',
  graduationYear: '2022',
  gpa: '3.8/4.0',
  skills: ['React', 'TypeScript', 'Node.js', 'Python', 'Tailwind CSS', 'GraphQL', 'MongoDB', 'AWS'],
  certifications: ['AWS Certified Developer Associate', 'Meta React Professional Certificate'],
  linkedinUrl: 'https://linkedin.com/in/alexjohnson',
  githubUrl: 'https://github.com/alexjohnson',
  portfolioUrl: 'https://alexjohnson.dev',
  phone: '+1 (415) 555-0123',
  location: 'San Francisco, CA'
};

export const MOCK_EMPLOYER: User = {
  id: 'e1',
  name: 'Sarah Connor',
  email: 'sarah@techflow.com',
  role: UserRole.EMPLOYER,
  avatarUrl: 'https://picsum.photos/id/65/100/100',
  title: 'HR Manager at TechFlow',
  status: 'Active',
  joinedDate: '2023-08-22'
};

export const MOCK_ADMIN: User = {
  id: 'a1',
  name: 'System Admin',
  email: 'admin@careerai.com',
  role: UserRole.ADMIN,
  avatarUrl: 'https://picsum.photos/id/66/100/100',
  title: 'Platform Administrator',
  status: 'Active',
  joinedDate: '2023-01-01'
};

export const MOCK_USERS_LIST: User[] = [
  MOCK_USER,
  MOCK_EMPLOYER,
  MOCK_ADMIN,
  {
    id: 'u2',
    name: 'Michael Chen',
    email: 'm.chen@example.com',
    role: UserRole.STUDENT,
    avatarUrl: 'https://picsum.photos/id/67/100/100',
    title: 'Data Science Student',
    bio: 'Aspiring data scientist with a passion for machine learning and AI. Currently exploring deep learning applications.',
    status: 'Pending',
    joinedDate: '2024-02-10',
    university: 'MIT',
    major: 'Data Science & Analytics',
    graduationYear: '2025',
    gpa: '3.9/4.0',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'SQL', 'R', 'Pandas', 'NumPy', 'Scikit-learn'],
    certifications: ['Google Data Analytics Certificate', 'Deep Learning Specialization (Coursera)'],
    linkedinUrl: 'https://linkedin.com/in/michaelchen',
    githubUrl: 'https://github.com/mchen',
    phone: '+1 (617) 555-0198',
    location: 'Boston, MA'
  },
  {
    id: 'e2',
    name: 'Global Tech Recruiting',
    email: 'hiring@globaltech.com',
    role: UserRole.EMPLOYER,
    avatarUrl: 'https://picsum.photos/id/68/100/100',
    title: 'Enterprise Recruiter',
    status: 'Inactive',
    joinedDate: '2023-12-05'
  },
  {
    id: 'u3',
    name: 'Jessica Day',
    email: 'jessica.d@example.com',
    role: UserRole.STUDENT,
    avatarUrl: 'https://picsum.photos/id/69/100/100',
    title: 'UX Researcher',
    bio: 'Creative UX/UI designer focused on human-centered design. I believe great design solves real problems.',
    status: 'Active',
    joinedDate: '2024-01-20',
    university: 'Carnegie Mellon University',
    major: 'Human-Computer Interaction',
    graduationYear: '2023',
    gpa: '3.7/4.0',
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping', 'Wireframing', 'Usability Testing', 'Design Systems'],
    certifications: ['Google UX Design Certificate', 'Nielsen Norman Group UX Certification'],
    linkedinUrl: 'https://linkedin.com/in/jessicaday',
    portfolioUrl: 'https://jessicaday.design',
    phone: '+1 (412) 555-0234',
    location: 'Pittsburgh, PA'
  },
  {
    id: 'u4',
    name: 'David Miller',
    email: 'david.m@example.com',
    role: UserRole.STUDENT,
    avatarUrl: 'https://picsum.photos/id/70/100/100',
    title: 'Junior Developer',
    bio: 'Full-stack developer passionate about building scalable web applications. Always eager to learn new technologies.',
    status: 'Active',
    joinedDate: '2024-03-01',
    university: 'UC Berkeley',
    major: 'Electrical Engineering & Computer Science',
    graduationYear: '2024',
    gpa: '3.6/4.0',
    skills: ['JavaScript', 'React', 'Node.js', 'Express', 'PostgreSQL', 'Docker', 'Git', 'REST APIs'],
    certifications: ['freeCodeCamp Full Stack Developer'],
    linkedinUrl: 'https://linkedin.com/in/davidmiller',
    githubUrl: 'https://github.com/dmiller',
    portfolioUrl: 'https://davidmiller.tech',
    phone: '+1 (510) 555-0156',
    location: 'Berkeley, CA'
  },
  {
    id: 'e3',
    name: 'StartUp Inc',
    email: 'founders@startup.io',
    role: UserRole.EMPLOYER,
    avatarUrl: 'https://picsum.photos/id/71/100/100',
    title: 'Hiring Manager',
    status: 'Pending',
    joinedDate: '2024-03-05'
  }
];

export const MOCK_APPLICANTS: Applicant[] = [
  {
    id: 'ap1',
    name: 'Jane Doe',
    email: 'jane@example.com',
    appliedDate: '1 day ago',
    matchScore: 92,
    status: 'New',
    avatarUrl: 'https://picsum.photos/id/101/100/100'
  },
  {
    id: 'ap2',
    name: 'John Smith',
    email: 'john@example.com',
    appliedDate: '2 days ago',
    matchScore: 78,
    status: 'Reviewing',
    avatarUrl: 'https://picsum.photos/id/102/100/100'
  },
  {
    id: 'ap3',
    name: 'Emily Chen',
    email: 'emily@example.com',
    appliedDate: '3 days ago',
    matchScore: 85,
    status: 'Interview',
    avatarUrl: 'https://picsum.photos/id/103/100/100'
  }
];

export const MOCK_STUDENT_APPLICATIONS = [
  {
    id: '101',
    jobId: '2',
    title: 'AI/ML Engineer',
    company: 'Nexus AI',
    logoUrl: 'https://picsum.photos/id/2/48/48',
    appliedDate: '3 days ago',
    status: 'Interview' as const,
  },
  {
    id: '102',
    jobId: '4',
    title: 'Backend Developer (Go)',
    company: 'StreamLine',
    logoUrl: 'https://picsum.photos/id/4/48/48',
    appliedDate: '1 week ago',
    status: 'Rejected' as const,
  },
  {
    id: '103',
    jobId: '1',
    title: 'Senior Frontend Engineer',
    company: 'TechFlow Solutions',
    logoUrl: 'https://picsum.photos/id/1/48/48',
    appliedDate: '2 weeks ago',
    status: 'Reviewing' as const,
  },
  {
    id: '104',
    jobId: '5',
    title: 'DevOps Engineer',
    company: 'CloudScale Systems',
    logoUrl: 'https://picsum.photos/id/5/48/48',
    appliedDate: '4 days ago',
    status: 'Applied' as const,
  },
  {
    id: '105',
    jobId: '7',
    title: 'Data Analyst',
    company: 'InsightLabs',
    logoUrl: 'https://picsum.photos/id/7/48/48',
    appliedDate: '5 days ago',
    status: 'Reviewing' as const,
  },
  {
    id: '106',
    jobId: '6',
    title: 'Mobile App Developer (React Native)',
    company: 'AppForge',
    logoUrl: 'https://picsum.photos/id/6/48/48',
    appliedDate: '1 week ago',
    status: 'Interview' as const,
  },
  {
    id: '107',
    jobId: '10',
    title: 'QA Automation Engineer',
    company: 'TestPro Solutions',
    logoUrl: 'https://picsum.photos/id/10/48/48',
    appliedDate: '2 weeks ago',
    status: 'Applied' as const,
  },
  {
    id: '108',
    jobId: '3',
    title: 'Product Designer',
    company: 'Creative Loops',
    logoUrl: 'https://picsum.photos/id/3/48/48',
    appliedDate: '3 weeks ago',
    status: 'Rejected' as const,
  },
  {
    id: '109',
    jobId: '13',
    title: 'Cloud Solutions Architect',
    company: 'CloudWorks Global',
    logoUrl: 'https://picsum.photos/id/13/48/48',
    appliedDate: '2 days ago',
    status: 'Applied' as const,
  }
];

export const INITIAL_CHAT_MESSAGE = "Hello! I'm your AI Career Counselor. How can I help you today? I can review your resume, suggest career paths, or help you prepare for an interview.";

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'job_match',
    title: 'Perfect Job Match!',
    message: 'Senior Frontend Engineer at TechFlow matches your profile (98%).',
    timestamp: 'Just now',
    read: false,
    link: PageView.JOB_DETAILS,
  },
  {
    id: 'n2',
    type: 'application_update',
    title: 'Application Status Update',
    message: 'Nexus AI has moved your application to the Interview stage.',
    timestamp: '2 hours ago',
    read: false,
    link: PageView.APPLICATION_HISTORY
  },
  {
    id: 'n3',
    type: 'system',
    title: 'Profile Tips',
    message: 'Adding a cover letter increases acceptance rates by 40%.',
    timestamp: '1 day ago',
    read: true,
    link: PageView.PROFILE
  },
  {
    id: 'n4',
    type: 'job_match',
    title: 'New Job Recommendation',
    message: 'DevOps Engineer at CloudScale Systems matches your skills (92%).',
    timestamp: '3 hours ago',
    read: false,
    link: PageView.JOB_RECOMMENDATIONS
  },
  {
    id: 'n5',
    type: 'system',
    title: 'Skill Recommendation',
    message: 'Learning Docker could unlock 15+ new job opportunities.',
    timestamp: '5 hours ago',
    read: false,
    link: PageView.RESUME_ANALYSIS
  },
  {
    id: 'n6',
    type: 'application_update',
    title: 'Interview Scheduled',
    message: 'AppForge has scheduled an interview for Mobile App Developer position.',
    timestamp: '6 hours ago',
    read: true,
    link: PageView.APPLICATION_HISTORY
  },
  {
    id: 'n7',
    type: 'job_match',
    title: 'Hot Job Alert',
    message: 'Cloud Solutions Architect position just posted - Apply now!',
    timestamp: '8 hours ago',
    read: true,
    link: PageView.JOB_SEARCH
  },
  {
    id: 'n8',
    type: 'system',
    title: 'Application Deadline',
    message: 'AI/ML Engineer application at Nexus AI closes in 2 days.',
    timestamp: '12 hours ago',
    read: true,
    link: PageView.APPLICATION_HISTORY
  },
  {
    id: 'n9',
    type: 'application_update',
    title: 'Application Received',
    message: 'CloudWorks Global has received your application.',
    timestamp: '1 day ago',
    read: true,
    link: PageView.APPLICATION_HISTORY
  },
  {
    id: 'n10',
    type: 'system',
    title: 'Profile Strength',
    message: 'Your profile is 85% complete. Add certifications to reach 100%.',
    timestamp: '2 days ago',
    read: true,
    link: PageView.PROFILE
  }
];
